stages:
  crawl:
    cmd: python crawler.py --save_dir data/raw --query "dog and cat" \ --num-image 20 \
    outs:
      - data/raw

  label:
    cmd: python auto_label.py --input_dir data/raw --output_dir data/labeled
    deps:
      - data/raw
    outs:
      - data/labeled

  process:
    cmd: python process.py --input_dir data/labeled --output_dir data/processed
    deps:
      - data/labeled
    outs:
      - data/processed